// Generated by Tools/generate_portable_resources.swift. Do not edit by hand.
import SwiftUI
import UIKit

public enum ChatPortableColors {
    private typealias Components = (red: CGFloat, green: CGFloat, blue: CGFloat, alpha: CGFloat)

    private static func dynamic(light: Components, dark: Components) -> Color {
        Color(uiColor: UIColor { traits in
            let value = traits.userInterfaceStyle == .dark ? dark : light
            return UIColor(red: value.red, green: value.green, blue: value.blue, alpha: value.alpha)
        })
    }

    public static let inputBG = dynamic(light: (0.949020, 0.952941, 0.960784, 1.000000), dark: (0.121569, 0.133333, 0.145098, 1.000000))
    public static let inputPlaceholderText = dynamic(light: (0.596078, 0.619608, 0.674510, 1.000000), dark: (0.443137, 0.478431, 0.525490, 1.000000))
    public static let mainBG = dynamic(light: (1.000000, 1.000000, 1.000000, 1.000000), dark: (0.000000, 0.000000, 0.000000, 1.000000))
    public static let mainCaptionText = dynamic(light: (0.505882, 0.549020, 0.600000, 1.000000), dark: (0.501961, 0.501961, 0.501961, 1.000000))
    public static let mainText = dynamic(light: (0.000000, 0.000000, 0.000000, 1.000000), dark: (1.000000, 1.000000, 1.000000, 1.000000))
    public static let menuBG = dynamic(light: (0.960784, 0.960784, 0.960784, 1.000000), dark: (0.137255, 0.141176, 0.145098, 1.000000))
    public static let menuText = dynamic(light: (0.380392, 0.396078, 0.443137, 1.000000), dark: (0.713725, 0.725490, 0.745098, 1.000000))
    public static let menuTextDelete = dynamic(light: (0.964706, 0.129412, 0.129412, 1.000000), dark: (0.992157, 0.231373, 0.247059, 1.000000))
    public static let messageFriendBG = dynamic(light: (0.921569, 0.929412, 0.941176, 1.000000), dark: (0.156863, 0.160784, 0.176471, 1.000000))
    public static let messageFriendTimeText = dynamic(light: (0.000000, 0.000000, 0.000000, 0.400000), dark: (1.000000, 1.000000, 1.000000, 0.400000))
    public static let messageMyBG = dynamic(light: (0.286275, 0.384314, 1.000000, 1.000000), dark: (0.352941, 0.443137, 1.000000, 1.000000))
    public static let messageMyTimeText = dynamic(light: (0.572549, 0.631373, 1.000000, 1.000000), dark: (1.000000, 1.000000, 1.000000, 0.400000))
    public static let messageReadStatus = dynamic(light: (0.000000, 0.478431, 1.000000, 1.000000), dark: (0.000000, 0.478431, 1.000000, 1.000000))
    public static let statusError = dynamic(light: (0.996078, 0.305882, 0.349020, 1.000000), dark: (1.000000, 0.368627, 0.400000, 1.000000))
    public static let statusGray = dynamic(light: (0.380392, 0.396078, 0.443137, 1.000000), dark: (0.713725, 0.725490, 0.745098, 1.000000))
}